---
title: "Application exercise"
subtitle: "01 - First dataviz"
output:
  xaringan::moon_reader:
    seal: false
    css: ["./slides.css", "./xaringan-themer.css"]
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightLines: true
      highlightStyle: solarized-light
      countIncrementalSlides: false
---

```{r child = "../../setup.Rmd"}
```

## AE 01 - First dataviz

You have two options for this exercise:

- Option 1: Voting patterns of countries in the UN General Assembly

- Option 2: COVID-19 fatality numbers across the globe

Pick one and complete it. Optionally, try the other one as well.

---

.your-turn[
**Option 1.**

- Go to [RStudio Cloud](https://rstudio.cloud/) and make sure you are in the "IDS 2021" space.
- Click on "New Project", then "New Project from Git Repository", and paste the following "URL of your Git Repository" into the text box (https://github.com/ids-s1-21/ae-01a-un-votes).
- In the Files pane (bottom right corner), spot the file called `unvotes.Rmd`. 
- Open it and click "Knit".
- Then...
  - Go back to the file and change your name on top (in the `yaml` -- we'll talk about what this means later) and knit again.
  - Change the country names to those you're interested in. Spelling and capitalization must match how the countries appear in the data, so take a peek at the Appendix to confirm spelling. 
  - Knit again. Voila, your first data visualization!
]

---

.your-turn[
**Option 2.**

- Go to [RStudio Cloud](https://rstudio.cloud/) and make sure you are in the "IDS 2021" space.
- Click on "New Project", then "New Project from Git Repository", and paste the following "URL of your Git Repository" into the text box (https://github.com/ids-s1-21/ae-01b-covid).
- In the Files pane (bottom right corner), spot the file called `covid.Rmd`.
- Open it and click "Knit".
- Then...
  - Go back to the file and change your name on top (in the `yaml` -- we'll talk about what this means later) and knit again.
  - Change the country names to those you're interested in. Spelling and capitalization must match how the countries appear in the data, so take a peek at the Appendix to confirm spelling. 
  - Knit again. Voila, your first data visualization!
]
